package com.tboostai_batch.util;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class CommonToolsTest {


    String sampleHtml = """
            
            <div translate=\\"no\\" class=\\"container\\" style=\\"color: #666;font-family: 'Roboto' , Helvetica, Arial, sans-serif;font-size: 16px;line-height: 1.5;-webkit-backface-visibility: hidden;text-align: left;font-weight: 300;margin: 0 auto;max-width: 1100px;margin-left: auto;margin-right: auto;\\">\\n <style>
                \\n@import url(https://fonts.googleapis.com/css?family=Roboto);
                \\n
              </style>\\n <main class=\\"content\\" style=\\"padding: 6%;\\">\\n\\n <div vocab=\\"https://schema.org/\\" typeof=\\"Product\\">\\n <h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">About this vehicle</h3>\\n <span property=\\"description\\">2019 McLaren 720s Coupe Performance, Pearl White interior with jet black alcantara/leather interior.\\n\\nThis McLaren 720s has every carbon option available from factory including the following additional add ons\\n\\n765LT carbon fiber front bumper and splitter \\n765LT carbon fiber front fenders with MSO LOUVERS \\n765lt carbon fiber side skirts and rocker panels \\n765lt carbon fiber rear bumper \\n765lt carbon fiber rear diffuser \\n765lt carbon fiber wing \\n\\n765lt cat back exhaust conversion (black tips)\\nNO DOWNPIPES (car still has the catylitic converters)\\nNO TUNE\\n\\nBrixton forged mono block ultra lightweight wheels \\n(Finished in polished carbon bronze)\\nBrand new PILOT SPORT 4S all around \\n\\n765lt upgraded accumulators (suspension component known for going bad on McLaren) \\n\\n720s/765lt full carbon fiber door sills \\n\\nJust serviced at McLaren\\n5th service complete! </span>\\n </div>\\n\\n\\n\\n <div id=\\"vehicleDescription\\">\\n <h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Vehicle Details</h3>\\n\\n <p id=\\"vehicleDescription-p1\\">|CLEAN TITLE NO ACCIDENTS|</p>\\n\\n <p id=\\"vehicleDescription-p2\\">PURCHASED AS CERTIFIED</p>\\n\\n <p id=\\"vehicleDescription-p3\\">2019 MCLAREN 720s PERFORMANCE MODEL</p>\\n\\n <p id=\\"vehicleDescription-p4\\">This unique McLaren is not your typical 720s. It has been aesthetically improved and converted to a 765LT with every carbon fiber element, suspension mechanism, and exhaust. This car has stock internals, NO tunes or catalytic converter modifications.</p>\\n\\n <p id=\\"vehicleDescription-p5\\">Essentially you will have the looks and performance of the 765LT for nearly half the price! Into consideration of the miles all the bugs and inconveniences mclarens can cause in the early years have been all worked out.</p>\\n\\n <p id=\\"vehicleDescription-p6\\">This is your chance to buy a ” 1 of 1” 720s that looks and performs like a 765LT for nearly the price of half.</p>\\n\\n <p id=\\"vehicleDescription-p7\\">REASONABLE OFFERS ACCEPTED, LOW BALLERS IGNORED. GUARANTEED WONT LAST!!</p>\\n\\n </div>\\n
                <hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;\\">\\n\\n\\n\\n\\n\\n <div id=\\"exteriorContainer\\">\\n <h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Exterior</h3>\\n\\n\\n <div class=\\"gallery\\" id=\\"exteriorImages\\" style=\\"padding-left: 0px;padding-top: 15px;margin: 0 auto;text-align: left;width: 100%;\\">\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/C0AAAOSwrDBm90FW/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/C0AAAOSwrDBm90FW/$_1.JPG?set_id=8800005007\\" alt=\\"image 1 of exterior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/wycAAOSwrp5m90Fi/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/wycAAOSwrp5m90Fi/$_1.JPG?set_id=8800005007\\" alt=\\"image 2 of exterior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/qCgAAOSwJhxm90GD/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/qCgAAOSwJhxm90GD/$_1.JPG?set_id=8800005007\\" alt=\\"image 3 of exterior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/XDAAAOSw8FJm90Hc/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/XDAAAOSw8FJm90Hc/$_1.JPG?set_id=8800005007\\" alt=\\"image 4 of exterior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/4SAAAOSwXKFm90Hk/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/4SAAAOSwXKFm90Hk/$_1.JPG?set_id=8800005007\\" alt=\\"image 5 of exterior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n </div>\\n\\n </div>\\n
                <hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;clear: both;\\">\\n\\n\\n <div id=\\"interiorContainer\\">\\n <h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Interior</h3>\\n\\n\\n <div class=\\"gallery\\" id=\\"interiorImages\\" style=\\"padding-left: 0px;padding-top: 15px;margin: 0 auto;text-align: left;width: 100%;\\">\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/N1wAAOSwE5tm90Lc/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/N1wAAOSwE5tm90Lc/$_1.JPG?set_id=8800005007\\" alt=\\"image 1 of interior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/PTAAAOSwuENm90Li/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/PTAAAOSwuENm90Li/$_1.JPG?set_id=8800005007\\" alt=\\"image 2 of interior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/FE8AAOSwvFVm90Lo/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/FE8AAOSwvFVm90Lo/$_1.JPG?set_id=8800005007\\" alt=\\"image 3 of interior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/1P0AAOSwQ7dm90NG/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/1P0AAOSwQ7dm90NG/$_1.JPG?set_id=8800005007\\" alt=\\"image 4 of interior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n <div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n <a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/FWgAAOSwq8Nm90NK/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
                        <img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/FWgAAOSwq8Nm90NK/$_1.JPG?set_id=8800005007\\" alt=\\"image 5 of interior\\" style=\\"width: auto;height:200px\\">
                      </a>\\n </div>\\n\\n </div>\\n\\n </div>\\n
                <hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;clear: both;\\">\\n\\n\\n\\n\\n\\n\\n <div id=\\"deposit_nonrefundable\\">\\n <h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\" id=\\"depositRefundTerms\\">Deposits are nonrefundable.</h3>\\n </div>\\n\\n
              </main>\\n <footer style=\\"text-align: center;font-size: 14.5px;padding-bottom: 3%;\\">Download the eBay Motors app <br>\\n <a href=\\"https://play.google.com/store/apps/details?id=com.ebay.motorsapp\\" style=\\"text-decoration: none;\\">
                  <img style=\\"border:0px;height:40px;width:auto;\\" src=\\"https://ir.ebaystatic.com/cr/v/c1/gp_store.png\\">
                </a>\\n <a href=\\"https://apps.apple.com/us/app/ebay-motors/id1456156090\\" style=\\"text-decoration: none;\\">
                  <img style=\\"border:0px;height:40px;width:auto;\\" src=\\"https://ir.ebaystatic.com/cr/v/c1/app_store.png\\">
                </a>\\n </footer>\\n </div>",
            """;

    String descOriginalText = """
            
            <div translate=\\"no\\" class=\\"container\\" style=\\"color: #666;font-family: 'Roboto', Helvetica, Arial, sans-serif;font-size: 16px;line-height: 1.5;-webkit-backface-visibility: hidden;text-align: left;font-weight: 300;margin: 0 auto;max-width: 1100px;margin-left: auto;margin-right: auto;\\">
            \\n<style>\\n@import url(https://fonts.googleapis.com/css?family=Roboto);\\n</style>\\n<main class=\\"content\\" style=\\"padding: 6%;\\">\\n\\n<div vocab=\\"https://schema.org/\\" typeof=\\"Product\\">\\n<h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">About this vehicle</h3>
            \\n<span property=\\"description\\">2019 McLaren 720s Coupe Performance, Pearl White interior with jet black alcantara/leather interior.\\n\\nThis McLaren 720s has every carbon option available from factory including the following additional add ons\\n\\n765LT carbon fiber front bumper and splitter \\n765LT carbon fiber front fenders with MSO LOUVERS 
            \\n765lt carbon fiber side skirts and rocker panels \\n765lt carbon fiber rear bumper \\n765lt carbon fiber rear diffuser \\n765lt carbon fiber wing \\n\\n765lt cat back exhaust conversion (black tips)\\nNO DOWNPIPES (car still has the catylitic converters)\\nNO TUNE\\n\\nBrixton forged mono block ultra lightweight wheels \\n(Finished in polished carbon bronze)\\nBrand new PILOT SPORT 4S all around 
            \\n\\n765lt upgraded accumulators (suspension component known for going bad on McLaren) \\n\\n720s/765lt full carbon fiber door sills \\n\\nJust serviced at McLaren\\n5th service complete! </span>\\n</div>\\n\\n\\n\\n<div id=\\"vehicleDescription\\">\\n<h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Vehicle Details</h3>\\n\\n<p id=\\"vehicleDescription-p1\\">|CLEAN TITLE NO ACCIDENTS|</p>
            \\n\\n<p id=\\"vehicleDescription-p2\\">PURCHASED AS CERTIFIED</p>\\n\\n<p id=\\"vehicleDescription-p3\\">2019 MCLAREN 720s PERFORMANCE MODEL</p>\\n\\n<p id=\\"vehicleDescription-p4\\">This unique McLaren is not your typical 720s. It has been aesthetically improved and converted to a 765LT with every carbon fiber element, suspension mechanism, and exhaust. This car has stock internals, NO tunes or catalytic converter modifications.</p>
            \\n\\n<p id=\\"vehicleDescription-p5\\">Essentially you will have the looks and performance of the 765LT for nearly half the price! Into consideration of the miles all the bugs and inconveniences mclarens can cause in the early years have been all worked out.</p>\\n\\n<p id=\\"vehicleDescription-p6\\">This is your chance to buy a ” 1 of 1” 720s that looks and performs like a 765LT for nearly the price of half.</p>
            \\n\\n<p id=\\"vehicleDescription-p7\\">REASONABLE OFFERS ACCEPTED, LOW BALLERS IGNORED. GUARANTEED WONT LAST!!</p>\\n\\n</div>\\n<hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;\\">\\n\\n\\n\\n\\n\\n<div id=\\"exteriorContainer\\">\\n<h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Exterior</h3>\\n\\n\\n<div class=\\"gallery\\" id=\\"exteriorImages\\" style=\\"padding-left: 0px;padding-top: 15px;margin: 0 auto;text-align: left;width: 100%;\\">
            \\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/C0AAAOSwrDBm90FW/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/C0AAAOSwrDBm90FW/$_1.JPG?set_id=8800005007\\" alt=\\"image 1 of exterior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/wycAAOSwrp5m90Fi/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\">
            <img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/wycAAOSwrp5m90Fi/$_1.JPG?set_id=8800005007\\" alt=\\"image 2 of exterior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/qCgAAOSwJhxm90GD/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/qCgAAOSwJhxm90GD/$_1.JPG?set_id=8800005007\\" alt=\\"image 3 of exterior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">
            \\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/XDAAAOSw8FJm90Hc/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/XDAAAOSw8FJm90Hc/$_1.JPG?set_id=8800005007\\" alt=\\"image 4 of exterior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/4SAAAOSwXKFm90Hk/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/4SAAAOSwXKFm90Hk/$_1.JPG?set_id=8800005007\\" alt=\\"image 5 of exterior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>
            \\n\\n</div>\\n\\n</div>\\n<hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;clear: both;\\">\\n\\n\\n<div id=\\"interiorContainer\\">\\n<h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\">Interior</h3>\\n\\n\\n<div class=\\"gallery\\" id=\\"interiorImages\\" style=\\"padding-left: 0px;padding-top: 15px;margin: 0 auto;text-align: left;width: 100%;\\">\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/N1wAAOSwE5tm90Lc/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/N1wAAOSwE5tm90Lc/$_1.JPG?set_id=8800005007\\" alt=\\"image 1 of interior\\" style=\\"width: auto;height:200px\\"></a>
            \\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/PTAAAOSwuENm90Li/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/PTAAAOSwuENm90Li/$_1.JPG?set_id=8800005007\\" alt=\\"image 2 of interior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/FE8AAOSwvFVm90Lo/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTIwMFgxNjAw/z/FE8AAOSwvFVm90Lo/$_1.JPG?set_id=8800005007\\" alt=\\"image 3 of interior\\" style=\\"width: auto;height:200px\\"></a>
            \\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/1P0AAOSwQ7dm90NG/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/1P0AAOSwQ7dm90NG/$_1.JPG?set_id=8800005007\\" alt=\\"image 4 of interior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n<div style=\\"display: inline; box-sizing: border-box;padding:5px;\\">\\n<a href=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/FWgAAOSwq8Nm90NK/$_57.JPG?set_id=8800005007\\" style=\\"text-decoration: none;color: #0058c9;\\"><img src=\\"https://i.ebayimg.com/00/s/MTYwMFgxMjAw/z/FWgAAOSwq8Nm90NK/$_1.JPG?set_id=8800005007\\" alt=\\"image 5 of interior\\" style=\\"width: auto;height:200px\\"></a>\\n</div>\\n\\n</div>\\n\\n</div>
            \\n<hr style=\\"background: none;margin: 3.0% 0;border: none;border-bottom: 1px solid #ddd;clear: both;\\">
            \\n\\n\\n\\n\\n\\n\\n<div id=\\"deposit_nonrefundable\\">\\n<h3 style=\\"font-size: 21px;font-weight: bold;color: black;\\" id=\\"depositRefundTerms\\">Deposits are nonrefundable.</h3>
            \\n</div>\\n\\n</main>\\n<footer style=\\"text-align: center;font-size: 14.5px;padding-bottom: 3%;\\">Download the eBay Motors app<br>\\n<a href=\\"https://play.google.com/store/apps/details?id=com.ebay.motorsapp\\" style=\\"text-decoration: none;\\"><img style=\\"border:0px;height:40px;width:auto;\\"  src=\\"https://ir.ebaystatic.com/cr/v/c1/gp_store.png\\"></a>\\n<a href=\\"https://apps.apple.com/us/app/ebay-motors/id1456156090\\" style=\\"text-decoration: none;\\"><img style=\\"border:0px;height:40px;width:auto;\\"  src=\\"https://ir.ebaystatic.com/cr/v/c1/app_store.png\\"></a>\\n</footer>\\n</div>"
            """;

    @Test
    void parseHTML() {

        Map<String, List<String>> result = CommonTools.parseHTML(sampleHtml);
        List<String> exactList = result.get("exactMatch");
        assertEquals(9, exactList.size());
        assertTrue(exactList.getFirst().contains("2019 McLaren 720s Coupe Performance"));
    }

    @Test
    void getDescriptionFromHTML() {
        Object object = CommonTools.getDescriptionFromHTML(descOriginalText);
        if (object instanceof String) {
            System.out.println(object);
        }
    }
}