spring.application.name=tboostAI-batch

server.port=${SERVER_PORT}

spring.main.web-application-type=servlet

# Eureka Common
eureka.client.service-url.defaultZone=${EUREKA_CONFIG_SERVICE_URL_DEFAULT_ZONE}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.cloud.discovery.enabled=true
eureka.instance.preferIpAddress=true

spring.batch.job.enabled=false

# Ebay API
EBAY_HOST=api.ebay.com
EBAY_TOKEN_URL=https://api.ebay.com/identity/v1/oauth2/token
EBAY_SEARCH_BY_CATEGORY_ID=buy/browse/v1/item_summary/search/
EBAY_SEARCH_BY_ITEM_ID=buy/browse/v1/item/
EBAY_CAR_TRUCK_US_CA_CATE_ID=6001

# Ebay settings
CLIENT_ID=${EBAY_CLIENT_ID}
CLIENT_SECRET=${EBAY_CLIENT_SECRET}
REFRESH_TOKEN=${EBAY_REFRESH_TOKEN}

# Google API Common
google.api.base-url=maps.googleapis.com/maps/api/geocode/json

spring.jpa.properties.hibernate.jdbc.batch_size=200
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.batch.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Automatic initialize tables when running batch
spring.batch.jdbc.initialize-schema=${BATCH_INIT_SCHEMA}

spring.aop.proxy-target-class=true

spring.main.allow-bean-definition-overriding=true

#OpenAI Project Key
openai.project.key=${OPENAI_PROJECT_KEY}
openai.project.chat.url=https://api.openai.com/v1/chat/completions

# Google API
google.api.key = ${GOOGLE_API_KEY}

# Redis Access Key
spring.data.redis.password=${REDIS_ACCESS_KEY_PRIMARY}

spring.profiles.active=${SPRING_PROFILES_ACTIVE}
