spring.config.activate.on-profile=prod
# MySQL
spring.datasource.url=jdbc:mysql://tboostai-core-db.mysql.database.azure.com/tboostai-core-db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.datasource.jdbcUrl=jdbc:mysql://tboostai-core-db.mysql.database.azure.com/tboostai-core-db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.datasource.username=${CORE_DB_USERNAME}
spring.datasource.password=${CORE_DB_PASSWORD}

# Redis
spring.data.redis.host=${REDIS_CLIENT}
spring.data.redis.port=6380
spring.data.redis.timeout=6000ms
spring.data.redis.database=0

spring.data.redis.ssl.enabled=true

# Batch DB
spring.batch.datasource.jdbcUrl=jdbc:mysql://tboostai-core-db.mysql.database.azure.com/tboostai-batch-schema-db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.batch.datasource.url=jdbc:mysql://tboostai-core-db.mysql.database.azure.com/tboostai-batch-schema-db?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
spring.batch.datasource.username=${BATCH_DB_USERNAME}
spring.batch.datasource.password=${BATCH_DB_PASSWORD}

spring.cloud.discovery.enabled=true

TBOOSTAI-LLM.ribbon.NIWSServerListClassName=com.netflix.loadbalancer.ConfigurationBasedServerList
TBOOSTAI-LLM.ribbon.listOfServers=${TBOOSTAI_LLM_URL}

