name: Trigger auto deployment for tboostai-batch

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/tboostai-batch-AutoDeployTrigger-711c58be-de0e-4274-84fa-9805ae361945.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TBOOSTAIBATCH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TBOOSTAIBATCH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TBOOSTAIBATCH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TBOOSTAIBATCH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TBOOSTAIBATCH_REGISTRY_PASSWORD }}
          containerAppName: tboostai-batch
          resourceGroup: tboostai-springcloud-prod
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


